name: Zip it

on:
  push:
    branches: ["gh-pages"]
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip it
        run: |
          zip -r destrier.zip . -x ".git*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: destrier-zip
          path: destrier.zip
